=== davidthorn/web-env/src/engine/Shopware/Components/Plugin/schema/cronjob.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:element name="cronjobs" type="cronjobsType"/>

    <xsd:complexType name="cronjobsType">
        <xsd:sequence>
            <xsd:element name="cronjob" type="cronjobType" minOccurs="1" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="cronjobType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="action" type="xsd:string"/>
            <xsd:element name="active" type="xsd:boolean"/>
            <xsd:element name="interval" type="xsd:int"/>
            <xsd:element name="disableOnError" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== davidthorn/web-env/src/tests/Unit/Components/Plugin/XmlReader/examples/cronjob/cronjob.xml
<?xml version="1.0" encoding="utf-8"?>
<cronjobs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../../../../../../../engine/Shopware/Components/Plugin/schema/cronjob.xsd">
    <cronjob>
        <name>Article Importer</name>
        <action>ImportArticle</action>
        <active>true</active>
        <interval>3600</interval>
        <disableOnError>true</disableOnError>
    </cronjob>
    <cronjob>
        <name>Order Export</name>
        <action>ExportOrder</action>
        <active>true</active>
        <interval>3600</interval>
        <disableOnError>false</disableOnError>
    </cronjob>
</cronjobs>
